### ISSUE TITLE
Re-test eSPI board before release

### ISSUE THREAD

**Issue by thorrak** [thorrak/tiltbridge#101]
The new code (especially the display reinit logic) needs to be tested on the eSPI board before release.

Specifically, I'm thinking of the code in PR #98 (though a full end-to-end test of a fully loaded TiltBridge would be a good idea)

**Comment by lbussy** [comment]
I have a board on the way - tomorrow I think.

**Comment by thorrak** [comment]
Assigning this to @lbussy since he's the only one with one of these boards right now.

**Comment by lbussy** [comment]
All seems good?  Moved to 5 lines (4 tilts) as well.  Inversion works, calling eSPI specific workflow tested.
