### ISSUE TITLE
TFT: Align Color Blocks

### ISSUE THREAD

**Issue by lbussy** [thorrak/tiltbridge#142]
Color Bars/blocks on TFT display are not aligned, they seem to be tacked on the end of the color text rather than justified in a column.

**Comment by thorrak** [comment]
I'm thinking swap the blocks for dots at the front of the color name

**Comment by lbussy** [comment]
That or create four columns (or both?)

**Comment by lbussy** [comment]
Working on this in `color_dots.`

**Comment by lbussy** [comment]
And I changed my mind and give you `colored_bars`.
