### ISSUE TITLE
AP on channel 3

### ISSUE THREAD

**Issue by lbussy** [thorrak/tiltbridge#158]
Apparently, the AP is coming up on channel 3 and is set at 40MHz.  The net effect is that it kills home APs on channels 1 and 6.

**Comment by thorrak** [comment]
Users just need to reconfigure their networks to accommodate tiltbridge.

**Comment by lbussy** [comment]
Need:

```
    // if true, enable autoreconnecting
    void          setWiFiAutoReconnect(boolean enabled);

    // set ap channel
    void          setWiFiAPChannel(int32_t channel);

    // set the country code for wifi settings, CN
    void          setCountry(String cc);
```

Also need to explore [`esp_wifi_set_bandwidth()`](https://docs.espressif.com/projects/esp-idf/en/v4.0/api-reference/network/esp_wifi.html#_CPPv422esp_wifi_set_bandwidth16wifi_interface_t16wifi_bandwidth_t).

**Comment by lbussy** [comment]
Here's the issue:

![image](https://user-images.githubusercontent.com/9092188/107151077-545d3380-6926-11eb-901e-f8af261ce03b.png)

**Comment by lbussy** [comment]
Either the AP is on channel 3 with a 40 MHz bandwidth or is on channels 1 and 5 (as my analyzer shows) with 20 MHz each.  I can't tell with my current tools.  All I can tell is there is no currently working method to get it to channel 1 and 20 MHz.  I am going to have to raise an issue on the WiFiManager repo when I get my sh*t together.

Also, I should probably try a straight AP example without the lib.

**Comment by lbussy** [comment]
Submitted [#1209](https://github.com/tzapu/WiFiManager/issues/1209) in the WiFiManager repo.
