### ISSUE TITLE
Request: Web Interface Dark Mode

### ISSUE THREAD

**Issue by SillyHats** [thorrak/tiltbridge#166]
It would be nice to have an option to make the web interface less bright

using TTGO USB-C with v1.0.2 from brewflasher (web interface about page says 1.0.1)

**Comment by lbussy** [comment]
Without a re-write of the page handling, there's not a real graceful way to change the Bootswatch theme on the fly without loading a white page each time and then changing it.

That said, there's plenty of browser plugins/add-ons which will do this for you.  Below is an example of the page in Firefox using "[Dark Reader](https://darkreader.org)."  They have plugins for Chrome, Safari, Firefox, and Edge.  It also allows you to set the mode (or customize it) for individual sites.

![image](https://user-images.githubusercontent.com/9092188/111302520-8185bb80-8621-11eb-9d3c-4160bfb8227d.png)
