### ISSUE TITLE
Null Brew Link

### ISSUE THREAD

**Issue by SillyHats** [thorrak/tiltbridge#167]
When using tilt bridge to send data only to google sheets there is a link to the beer name (in this case 3rd) that goes to /null resulting in a 404 error

![image](https://user-images.githubusercontent.com/5270556/111195860-14c3e000-8593-11eb-9c28-12401ed793d5.png)

![image](https://user-images.githubusercontent.com/5270556/111195919-22796580-8593-11eb-9186-4073132e70a1.png)

using TTGO USB-C with v1.0.1 from brewflasher

**Comment by lbussy** [comment]
I suspect then that the URL is malformed?  If you can watch in the serial monitor, you will see the transaction.  Aside from that, the link will not be correct till after the sheet sends/receives once.

**Comment by SillyHats** [comment]
Thanks! You are correct. 

That text links to the google sheet after the second data point is logged.

**Comment by lbussy** [comment]
Good deal.

I should have put a better link in there - I was thrilled to have the damned workflow work, however, and I forgot. :)

**Comment by SillyHats** [comment]
Somebody needs to be the [DAU](https://www.acronymfinder.com/D%C3%BCmmster-Anzunehmender-User-(German%3a-Dumbest-Assumable-User%3b-play-on-words%2c-see-GAU)-(DAU).html) to find such bugs.

**Comment by thorrak** [comment]
> Somebody needs to be the [DAU](https://www.acronymfinder.com/D%C3%BCmmster-Anzunehmender-User-(German%3a-Dumbest-Assumable-User%3b-play-on-words%2c-see-GAU)-(DAU).html) to find such bugs.

Normally I can be trusted to act in that role... 😆
