### ISSUE TITLE
Handle Blank URL more Gracefully

### ISSUE THREAD

**Issue by lbussy** [thorrak/tiltbridge#168]
Per #167, we should do a better job of handling the blank URL before the update is received.  Yes, they can wait a few minutes BUT these are often folks who are excited to see it working (me included) and can cause confusion.

**Comment by lbussy** [comment]
This change has been pushed to devel.  There are a few other changes pending in devel so this will get done when @thorrak gets around to it next.

**Comment by thorrak** [comment]
Merged into master
