### ISSUE TITLE
Request - OLED: Less logo, more stats

### ISSUE THREAD

**Issue by SillyHats** [thorrak/tiltbridge#169]
The logo and temp/gravity flash back and forth for what appears to be 10 seconds of stats followed by 5 seconds of logo, foiling a quick glance for the stats. Could the interval of how long the stats are on the display be longer to facilitate reading the numbers by default or option configeration?

using TTGO USB-C with v1.0.2 from brewflasher (web interface about page says 1.0.1)

**Comment by lbussy** [comment]
I changed the logo time to 2 seconds and that's been merged to devel.  There are a few other changes pending in devel so this will get done when @thorrak gets around to it next.

**Comment by thorrak** [comment]
This is now merged to master
