### ISSUE TITLE
Serial Monitor Confustion between Brewfather and Brewer's Friend

### ISSUE THREAD

**Issue by SillyHats** [thorrak/tiltbridge#177]
While looking through the serial monitor log for any more hints on why the tilt bridge keeps falling off my wifi and not getting back on I noticed this.

The log results for Brewfather refer to Brewer's Friend even though that target is not enabled

10:09:54.338 ->      45253 V: Calling send to Brewfather.
10:09:54.338 ->      45255 V: Tilt loaded with color name: Orange
10:09:55.323 ->      46264 V: Connecting to: log.brewfather.net on port 80
10:09:55.417 ->      46332 V: Connected to: log.brewfather.net.
10:09:55.417 ->      46334 V: POST /stream?id=xxxxxxxxxxxxxxx HTTP/1.1
10:09:55.417 ->      46345 V: Host: log.brewfather.net:80
10:09:55.417 ->      46349 V: Connection: close
10:09:55.417 ->      46351 V: Content-Length: 114
10:09:55.417 ->      46355 V: Content-Type: application/json
10:09:55.417 ->      46358 V: End headers.
10:09:55.746 ->      46654 V: Status: HTTP/1.1 200 OK
10:09:55.746 ->      46655 V: Post to log.brewfather.net was successful.
10:09:55.746 ->      46659 N: **Completed send to Brewer's Friend.   <-------------------------------**
10:10:14.321 ->      65262 V: Free Heap: 140236, Largest contiguous block: 97392, Frag: 31%

Brew Status posting process has the same name throughout

10:10:15.676 ->      66633 V: Calling send to Brew Status.
10:10:15.722 ->      66639 V: Connecting to: www.brewstat.us on port 443
10:10:15.909 ->      66828 V: Connected to: www.brewstat.us.
10:10:15.909 ->      66830 V: POST /tilt/xxxxxxxxxxxxxx/log HTTP/1.1
10:10:15.909 ->      66838 V: Host: www.brewstat.us:443
10:10:15.909 ->      66843 V: Connection: close
10:10:15.909 ->      66845 V: Content-Length: 84
10:10:15.909 ->      66848 V: Content-Type: application/x-www-form-urlencoded
10:10:15.909 ->      66851 V: End headers.
10:10:16.327 ->      67240 V: Status: HTTP/1.1 200 OK
10:10:16.327 ->      67241 V: Post to www.brewstat.us was successful.
10:10:16.327 ->      67245 N: Completed send to Brew Status.
10:10:44.340 ->      95262 V: Free Heap: 140140, Largest contiguous block: 97392, Frag: 31%

**Comment by thorrak** [comment]
The Brewers Friend and Brewfather code is the same between both targets - there's actually a flag for "Does BF mean Brewfather or Brewers Friend". That sounds like we missed a log entry somewhere, but otherwise it sounds like its working correctly.

That said, leave this issue open so we remember to get the log entries updated to have the appropriate text. ;)
