### ISSUE TITLE
Add Grainfather support

### ISSUE THREAD

**Issue by teanooki** [thorrak/tiltbridge#179]
It would be great having the ability to send data to Grainfather. I managed to communicate with their API on the console:

- Add Tilt device under Equipment
- Copy the individual url you can find by pressing the information button. Example: https://community.grainfather.com/iot/XXXX-XXXX/tilt
- Send JSON in POST body `{"SG":1.102, "Temp":23.9, "Unit": "C"}`. Once per 15 minutes,

**Example**
`curl -H 'Content-Type: application/json' -H 'Accept: application/json' --data '{"SG":1.102, "Temp":23.9, "Unit":"C"}' -X POST https://community.grainfather.com/iot/XXXX-XXXX/tilt`

Result:
<code>
HTTP/2 201
{"result":"success"}
</code>

Error:
<code>
HTTP/2 429
{
    "message": "Too Many Attempts."
}
</code>

**Feature request**
- New option to add an individual URL for each Tilt color in the logging settings
- Send data as described to Grainfather once per 15 minutes

**Data received in Grainfather**
![Selection_005](https://user-images.githubusercontent.com/9087820/113563565-318a8b00-9608-11eb-8e50-3972f129a658.png)

**Comment by thorrak** [comment]
I already have Grainfather as a supported target in [Fermentrack](https://github.com/thorrak/fermentrack), it shouldn't be an issue to get this added to TiltBridge as well.

**Comment by thorrak** [comment]
This is now merged to master
