### ISSUE TITLE
tiltbridge.com issue

### ISSUE THREAD

**Issue by TaplistIOTeam** [thorrak/tiltbridge#191]
Just noticed there seems to be an error serving `tiltbridge.com`:

![image](https://user-images.githubusercontent.com/41236989/114467054-4f7f5f00-9bb7-11eb-84e2-c2c77ce6d904.png)

**Comment by thorrak** [comment]
...welp. I’ll take a look momentarily - I know exactly what is wrong.

**Comment by thorrak** [comment]
Fixed!
