### ISSUE TITLE
WLAN not connecting

### ISSUE THREAD

**Issue by scriper88** [thorrak/tiltbridge#196]
Hi!

I installed an ESP32 and Tiltbrige with BrewFlasher.

Unfortunately, he cannot connect to the WiFi.

I have even installed an extra access point to have my own SSID (otherwise I have the same for 2.4 and 5 GHz).

I noticed the following: After the WLAN configuration, the ESP does >not< restart. Even restarting by hand does not help, he always opens his own TiltBridgeAP access point. If I then connect to it, I can see that the WiFi configuration has been saved!

I have already reinstalled several times including "erase, wipes all data", baud rate is 115200. I have also tried other power supplies / cables.
Do you have any ideas?

I find this under Info:

Not Connected to TP-Link_A11C
esp32

Uptime
4 Mins 51 Secs
Chip ID
5cc40a24
Chip Rev
1
Flash Size
8388608 bytes
PSRAM Size
0 bytes
SDK Version
v3.3.4-404-g7e63061fa
CPU Frequency
240MHz
Memory - Free Heap
158772 bytes available
Memory - Sketch Size
Used / Total bytes
1447808 / 4593536
Not Connected to TP-Link_A11C
esp32

Uptime
4 Mins 51 Secs
Chip ID
5cc40a24
Chip Rev
1
Flash Size
8388608 bytes
PSRAM Size
0 bytes
SDK Version
v3.3.4-404-g7e63061fa
CPU Frequency
240MHz
Memory - Free Heap
158772 bytes available
Memory - Sketch Size
Used / Total bytes
1447808 / 4593536

**Comment by thorrak** [comment]
Apologies for the delays in addressing this issue. I've changed out the WiFi manager libraries in v1.0.3, which hopefully solves this issue. If you are still having this issue and want to test it out, v1.0.3 should be available (as beta) in BrewFlasher. If you test it, and the issue reoccurs, feel free to come back and post in this issue.
