### ISSUE TITLE
Tiltbridge show the preview beer

### ISSUE THREAD

**Issue by mdasoft** [thorrak/tiltbridge#197]
Hi!
I'd realized that Tiltbridge dashboard shows the preview beer name, not the current beer which is fermenting. Data about fermentation is ok, it's updated properly, but the beer name is wrong.
It's not important for me, I just want to comment it here :-)

Thanks for your well done work!

**Comment by mdasoft** [comment]
Hi!
These are the screenshot, one is the Tiltbridge info, the second one is my Brewstatus profile. The beer which is under fermentation is "Double Yeast Saison", but Tiltbridge shows "Kveik IPA 2021", the previews beer I'd brewed.

![Captura de pantalla 2021-10-16 a las 17 31 27](https://user-images.githubusercontent.com/14077236/137593396-9de1defb-c28a-4c6b-a0ad-413d958231d7.png)
![Captura de pantalla 2021-10-16 a las 17 31 55](https://user-images.githubusercontent.com/14077236/137593398-e590512d-edb5-4d61-ab1f-b28571885e31.png)

Cheers! :-)

**Comment by thorrak** [comment]
How are you updating the name of the beer being fermented? On the TiltBridge or in Brewstatus?

For the previous brew, did you use Google Sheets? Are you using Google Sheets for the current beer?

**Comment by lbussy** [comment]
I'm 98% sure the only place that's going to get the brew name is from GSheets.  The reason is that name is supposed to be a link back to that sheet.  If you click on it, you will be taken to your sheet where you will see this to be true.

Go to Settings->Target Settings->Google Sheets and delete the name of the brew there, or change it, whichever you prefer.

**Comment by mdasoft** [comment]
> I'm 98% sure the only place that's going to get the brew name is from GSheets. The reason is that name is supposed to be a link back to that sheet. If you click on it, you will be taken to your sheet where you will see this to be true.
> 
> Go to Settings->Target Settings->Google Sheets and delete the name of the brew there, or change it, whichever you prefer.

That's true!
I've remember that in my previews brew I was trying to link the Tilt with my Google Sheets (like I used to do with an old Android mobile until it died and started to use Tiltbridge...), but it never worked. So I come back to Brewstatus again, but I didn't remove the beer name from Google Sheets settings.

Thanks!
