### ISSUE TITLE
Degrees Celsius or Fahrenheit switch

### ISSUE THREAD

**Issue by sjd08** [thorrak/tiltbridge#24]
Create a switch in settings to change between degrees Celsius and Fahrenheit. This setting should determine how the Tilts temperature is displayed in the Home screen.

**Comment by brookwarner** [comment]
+1

**Comment by ricnewton** [comment]
I have an implementation of switching between Celsius and Fahrenheit here: https://github.com/ricnewton/tiltbridge/tree/temperature-units

Happy to raise a PR if wanted

**Comment by thorrak** [comment]
> I have an implementation of switching between Celsius and Fahrenheit here: https://github.com/ricnewton/tiltbridge/tree/temperature-units
> 
> Happy to raise a PR if wanted

Please do! :)
