### ISSUE TITLE
Does an ideaspark® ESP32 OLED also fit?

### ISSUE THREAD

**Issue by fkroepfl** [thorrak/tiltbridge#240]
Does an ideaspark® ESP32 Development Board with 0.96 Inch OLED Display,CH340,WiFi+BLE also fit to install Tiltbridge?

e.g. https://www.ebay.com/itm/176053628906

thx.

/FJ

![image](https://github.com/thorrak/tiltbridge/assets/6333880/feda9efe-f3d4-40f9-bfd8-dc0c0144e0b1)

**Comment by thorrak** [comment]
Although I have never used this board and thus cannot guarantee anything, it does appear that I already attempt to initialize the correct pins this board requires: https://github.com/thorrak/tiltbridge/blob/e06746762e5ab6f6f713ceaebae0e58a7bda94e4/src/bridge_lcd.cpp#L72

**Comment by fkroepfl** [comment]
That sounds good ... 🤗
Thank you very much for the code x-check.
