### ISSUE TITLE
Add to the docs: Case design for "ideaspark® ESP32 Development Board with 0.96 Inch OLED Display"

### ISSUE THREAD

**Issue by fkroepfl** [thorrak/tiltbridge#257]
For your information: 

There is another case design for **ideaspark® ESP32 Development Board with 0.96 Inch OLED Display** available.
- https://www.printables.com/model/773441-esp32-oled-box

It may make sense to include this information in the TiltBridge hardware documentation:
- https://tiltbridge.readthedocs.io/en/master/hardware.html#oled-cases

**Comment by thorrak** [comment]
This has now been added, and will show in the next docs build after #246 gets merged.
