### ISSUE TITLE
Tilt Version Fails to Reset

### ISSUE THREAD

**Issue by lbussy** [thorrak/tiltbridge#51]
Scenario:

- Two Tilts of the same color
- One Pro
- One < Pro
- Log for a time with the Pro
- Turn the Pro off
- Turn the non-Pro on
- Observe the readings are off by a factor of 10

I suspect the version checking is only done once.  This could be done each time (cheap enough processing remaining) or at the least, it should be done on a timer.

Also, gravity smoothing gets very weird.  It might be cleanest to track on a MAC address and reset the buffer if the MAC changes.

**Comment by pletch** [comment]
I assume you must be turning the non-Pro on before the Pro actually expires and disappears from the dashboard?

**Comment by lbussy** [comment]
> I assume you must be turning the non-Pro on before the Pro actually expires and disappears from the dashboard?

Not sure, what's the timeout?

**Comment by pletch** [comment]
5 minutes

**Comment by lbussy** [comment]
I'm an edge case!   (We always knew that.)

I can confirm it resets as you intended and that you have also added some additional logic to address my "color issues."  This should go away completely when John and I have a chance to swap our Tilt Pros.

Closing.
